update workflow [skip ci]

diff --git a/.github/workflows/demo-create-account.yml b/.github/workflows/demo-create-account.yml
--- a/.github/workflows/demo-create-account.yml
+++ b/.github/workflows/demo-create-account.yml
@@ -12,13 +12,12 @@ jobs:
   demo-create-account:
     runs-on: ubuntu-latest
     env:
-      STACK_NAME: spacelift/${{fromJson(inputs.port_payload).payload.action.invocationMethod.repo}}
-      ACCOUNT_NAME: aws-c2-${{fromJson(inputs.port_payload).payload.properties.solution_name}}-${{fromJson(inputs.port_payload).payload.properties.account_environment}}
-      ACCOUNT_EMAIL: accounts+aws-c2-${{fromJson(inputs.port_payload).payload.properties.solution_name}}-${{fromJson(inputs.port_payload).payload.properties.account_environment}}@nuvibit.com
+      STACK_NAME: ${{fromJson(inputs.port_payload).payload.action.invocationMethod.repo}}
       ACCOUNT_ENVIRONMENT: ${{fromJson(inputs.port_payload).payload.properties.account_environment}}
       COST_CENTER: ${{fromJson(inputs.port_payload).payload.properties.cost_center_id}}
       SECURITY_CONTACT_EMAIL: ${{fromJson(inputs.port_payload).payload.properties.security_contact_email}}
-      CREATE_TERRAFORM_PIPELINE: ${{fromJson(inputs.port_payload).payload.properties.create_terraform_pipeline}}
+      ACCOUNT_NAME: aws-c2-${{fromJson(inputs.port_payload).payload.properties.solution_name}}-${{fromJson(inputs.port_payload).payload.properties.account_environment}}
+      ACCOUNT_EMAIL: accounts+aws-c2-${{fromJson(inputs.port_payload).payload.properties.solution_name}}-${{fromJson(inputs.port_payload).payload.properties.account_environment}}@nuvibit.com
       PORT_USER_EMAIL: ${{fromJson(inputs.port_payload).trigger.by.user.email}}
       PORT_USER_FIRST_NAME: ${{fromJson(inputs.port_payload).trigger.by.user.firstName}}
       PORT_USER_LAST_NAME: ${{fromJson(inputs.port_payload).trigger.by.user.lastName}}
@@ -43,7 +42,7 @@ jobs:
       - name: Update Account List - Add new account
         run: |
           account_list_path="account_list_workloads.json"
-          account_list=$(cat account_list_workloads.json)
+          account_list=$(cat $account_list_path)
           new_account=$(cat <<EOF 
           {
               "account_name": "$ACCOUNT_NAME",
@@ -65,8 +64,7 @@ jobs:
                   }
               ],
               "customer_values": {
-                "additional_oidc_subjects": [],
-                "create_terraform_pipeline": $CREATE_TERRAFORM_PIPELINE
+                "additional_oidc_subjects": []
               }
           }
           EOF)
@@ -78,7 +76,7 @@ jobs:
         id: pull-request
         uses: peter-evans/create-pull-request@v6
         with:
-          commit-message: "adding aws account '${{ env.ACCOUNT_NAME }}'"
+          commit-message: "adding aws account '${{ env.ACCOUNT_NAME }}' [skip ci]"
           committer: GitHub <noreply@github.com>
           author: ${{ env.PORT_USER_FIRST_NAME }} ${{ env.PORT_USER_LAST_NAME }} <${{ env.PORT_USER_EMAIL }}>
           title: "create aws account '${{ env.ACCOUNT_NAME }}'"
@@ -105,14 +103,15 @@ jobs:
         id: wait-for-plan
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
-          checkName: ${{ env.STACK_NAME }}
+          checkName: spacelift/${{ env.STACK_NAME }}
           ref: ${{ steps.pull-request.outputs.pull-request-head-sha }}
           timeoutSeconds: 600
           intervalSeconds: 10
 
       # update run logs in getport.io - checks successful
-      - name: Update Run Logs - Checks Successful
-        if: steps.wait-for-plan.outputs.conclusion == 'success'
+      - name: Update Run Logs - Checks Successful$
+        # if: steps.wait-for-plan.outputs.conclusion == 'success'
+        if: contains(fromJson('["success", "neutral"]'), steps.wait-for-plan.outputs.conclusion)
         uses: port-labs/port-github-action@v1
         with:
           clientId: ${{ secrets.PORT_CLIENT_ID }}
@@ -123,7 +122,8 @@ jobs:
 
       # update run logs in getport.io - checks failed
       - name: Update Run Logs - Checks Failed
-        if: steps.wait-for-plan.outputs.conclusion != 'success'
+        # if: steps.wait-for-plan.outputs.conclusion != 'success'
+        if: contains(fromJson('["failure", "timed_out", "action_required"]'), steps.wait-for-plan.outputs.conclusion)
         uses: port-labs/port-github-action@v1
         with:
           clientId: ${{ secrets.PORT_CLIENT_ID }}
@@ -134,7 +134,8 @@ jobs:
 
       # update run logs in getport.io - approve pr
       - name: Update Run Logs - Approve PR
-        if: steps.wait-for-plan.outputs.conclusion == 'success'
+        # if: steps.wait-for-plan.outputs.conclusion == 'success'
+        if: contains(fromJson('["success", "neutral"]'), steps.wait-for-plan.outputs.conclusion)
         uses: port-labs/port-github-action@v1
         with:
           clientId: ${{ secrets.PORT_CLIENT_ID }}
@@ -144,7 +145,8 @@ jobs:
           logMessage: "👍 approving pull request..."
     
       - name: Approve Pull Request
-        if: steps.wait-for-plan.outputs.conclusion == 'success'
+        # if: steps.wait-for-plan.outputs.conclusion == 'success'
+        if: contains(fromJson('["success", "neutral"]'), steps.wait-for-plan.outputs.conclusion)
         uses: hmarr/auto-approve-action@v4
         with:
           pull-request-number: ${{ steps.pull-request.outputs.pull-request-number }}
@@ -152,7 +154,8 @@ jobs:
 
       # update run logs in getport.io - merge pr
       - name: Update Run Logs - Merge PR
-        if: steps.wait-for-plan.outputs.conclusion == 'success'
+        # if: steps.wait-for-plan.outputs.conclusion == 'success'
+        if: contains(fromJson('["success", "neutral"]'), steps.wait-for-plan.outputs.conclusion)
         uses: port-labs/port-github-action@v1
         with:
           clientId: ${{ secrets.PORT_CLIENT_ID }}
@@ -162,7 +165,8 @@ jobs:
           logMessage: "⛙ merging pull request..."
 
       - name: Merge Pull Request
-        if: steps.wait-for-plan.outputs.conclusion == 'success'
+        # if: steps.wait-for-plan.outputs.conclusion == 'success'
+        if: contains(fromJson('["success", "neutral"]'), steps.wait-for-plan.outputs.conclusion)
         uses: juliangruber/merge-pull-request-action@v1.3.1
         id: merge-pr
         continue-on-error: true
@@ -205,45 +209,50 @@ jobs:
           runId: ${{ env.PORT_RUN_ID }}
           logMessage: "⏲️ waiting for creation of aws account '${{ env.ACCOUNT_NAME }}'..."
 
-      # TODO: spacelift doesn't inject github check outside of pull requests
-      # # wait for pull request checks to succeed
-      # - name: Wait For Account Creation
-      #   if: ${{ steps.merge-pr.outcome == 'success' }}
-      #   uses: fountainhead/action-wait-for-check@v1.2.0
-      #   id: wait-for-apply
-      #   with:
-      #     token: ${{ secrets.GITHUB_TOKEN }}
-      #     checkName: ${{ env.STACK_NAME }}
-      #     ref: ${{ steps.merge-pr.outputs.commit }}
-      #     timeoutSeconds: 600
-      #     intervalSeconds: 10
+      # wait for pull request checks to succeed
+      - name: Wait For Account Creation
+        if: ${{ steps.merge-pr.outcome == 'success' }}
+        uses: fountainhead/action-wait-for-check@v1.2.0
+        id: wait-for-apply
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          checkName: spacelift/${{ env.STACK_NAME }}/tracked
+          ref: ${{ steps.merge-pr.outputs.commit }}
+          timeoutSeconds: 600
+          intervalSeconds: 10
 
       # update run logs in getport.io - account created
       - name: Update Run Logs - Account Created
         # if: steps.wait-for-apply.outputs.conclusion == 'success'
+        if: contains(fromJson('["success", "neutral"]'), steps.wait-for-apply.outputs.conclusion)
         uses: port-labs/port-github-action@v1
         with:
           clientId: ${{ secrets.PORT_CLIENT_ID }}
           clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
           operation: PATCH_RUN
           runId: ${{ env.PORT_RUN_ID }}
-          logMessage: "✅ aws account '${{ env.ACCOUNT_NAME }}' is currently beeing created!"
+          logMessage: "✅ aws account '${{ env.ACCOUNT_NAME }}' successfully created!"
 
       # update run logs in getport.io - account creation failed
-      # - name: Update Run Logs - Account Creation Failed
-      #   # if: steps.wait-for-apply.outputs.conclusion != 'success'
-      #   uses: port-labs/port-github-action@v1
-      #   with:
-      #     clientId: ${{ secrets.PORT_CLIENT_ID }}
-      #     clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
-      #     operation: PATCH_RUN
-      #     runId: ${{ env.PORT_RUN_ID }}
-      #     logMessage: "❌ aws account '${{ env.ACCOUNT_NAME }}' failed to create."
+      - name: Update Run Logs - Account Creation Failed
+        # if: steps.wait-for-apply.outputs.conclusion != 'success'
+        if: contains(fromJson('[["failure", "timed_out", "action_required"]]'), steps.wait-for-apply.outputs.conclusion)
+        uses: port-labs/port-github-action@v1
+        env: 
+          ACCOUNT_NAME: aws-c2-${{fromJson(inputs.port_payload).payload.properties.solution_name}}-${{fromJson(inputs.port_payload).payload.properties.account_environment}}
+          ACCOUNT_EMAIL: accounts+aws-c2-${{fromJson(inputs.port_payload).payload.properties.solution_name}}-${{fromJson(inputs.port_payload).payload.properties.account_environment}}@nuvibit.com
+        with:
+          clientId: ${{ secrets.PORT_CLIENT_ID }}
+          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
+          operation: PATCH_RUN
+          runId: ${{ env.PORT_RUN_ID }}
+          logMessage: "❌ aws account '${{ env.ACCOUNT_NAME }}' failed to create."
 
       # update getport.io catalog
       - name: Update Catalog
         id: port-entity
         # if: steps.wait-for-apply.outputs.conclusion == 'success'
+        if: contains(fromJson('["success", "neutral"]'), steps.wait-for-apply.outputs.conclusion)
         uses: port-labs/port-github-action@v1
         with:
           clientId: ${{ secrets.PORT_CLIENT_ID }}
@@ -263,16 +272,17 @@ jobs:
               "security_contact": "${{ env.SECURITY_CONTACT_EMAIL }}"
             }
 
-      # - name: Account Creation Outcome
-      #   if: steps.wait-for-apply.outputs.conclusion != 'success'
-      #   run: exit 1
+      - name: Account Creation Outcome
+        # if: steps.wait-for-apply.outputs.conclusion != 'success'
+        if: contains(fromJson('[["failure", "timed_out", "action_required"]]'), steps.wait-for-apply.outputs.conclusion)
+        run: exit 1
 
   workflow-summary:
     needs:
       - demo-create-account
     runs-on: ubuntu-latest
     if: ${{ always() }}
-    env:
+    env: 
       ACCOUNT_NAME: aws-c2-${{fromJson(inputs.port_payload).payload.properties.solution_name}}-${{fromJson(inputs.port_payload).payload.properties.account_environment}}
       PORT_RUN_ID: ${{fromJson(inputs.port_payload).context.runId}}
 
